import { Card, CardContent } from "@/components/ui/card";
import {
  FileText,
  Download,
  StarsIcon,
  Zap,
  Shield,
  Globe,
} from "lucide-react";

const Features = () => {
  const features = [
    {
      icon: FileText,
      title: "Professional Templates",
      description:
        "Choose from beautifully designed, ATS-friendly resume templates",
    },
    {
      icon: Zap,
      title: "Lightning Fast",
      description:
        "Build your resume in minutes with our intuitive drag-and-drop interface",
    },
    {
      icon: Download,
      title: "Instant PDF Export",
      description:
        "Download your resume as a high-quality PDF ready for job applications",
    },
    {
      icon: Shield,
      title: "Secure & Private",
      description: "Your data is encrypted and stored securely in the cloud",
    },
    {
      icon: StarsIcon,
      title: "AI-Powered summaries",
      description:
        "Get personalized resume summaries generated by AI to highlight your strengths",
    },
    {
      icon: Globe,
      title: "Access Anywhere",
      description: "Work on your resume from any device, anywhere in the world",
    },
  ];

  return (
    <section id="features" className="py-20 px-4 bg-white">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-gray-900 mb-4">
            Why Choose ResumeCloud?
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Everything you need to create a professional resume that stands out
            from the crowd
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <Card
              key={index}
              className="group hover:shadow-lg transition-all duration-300 border-0 shadow-md"
            >
              <CardContent className="p-8 text-center">
                <div className="bg-blue-100 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6 group-hover:bg-blue-200 transition-colors">
                  <feature.icon className="w-8 h-8 text-blue-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-4">
                  {feature.title}
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  {feature.description}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
